# Generated by Django 5.0 on 2023-12-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('clubPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productType', models.CharField(max_length=255)),
                ('productSku', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
